[package]
name = "httputa"
version = "0.1.0"
authors = ["OhmRee <omrisim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
strum = "0.19.2"
strum_macros = "0.19.2"
thiserror = "1.0.20"
